# Generated by Django 5.0 on 2024-02-05 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.template.defaultfilters import slugify

def create_interests(apps, schema):
    Interest = apps.get_model("registration", "Interest")

    interests = [
        Interest(name="Hiking", slug=slugify("Hiking")),
        Interest(name="Biking", slug=slugify("Biking")),
        Interest(name="Swimming", slug=slugify("Swimming")),
        Interest(name="Reading", slug=slugify("Reading")),
        Interest(name="Writing", slug=slugify("Writing")),
        Interest(name="Photography", slug=slugify("Photography")),
        Interest(name="Travelling", slug=slugify("Travelling")),
        Interest(name="Sports", slug=slugify("Sports")),
        Interest(name="Yoga", slug=slugify("Yoga")),
        Interest(name="Art", slug=slugify("Art")),
    ]
    Interest.objects.bulk_create(interests)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("slug", models.SlugField(editable=False)),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="interests", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="Birth date"),
                ),
                (
                    "gender",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "Male"), (2, "Female"), (3, "Other")],
                        null=True,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "experience_level",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "Entry level"), (2, "Manager"), (3, "Other")],
                        null=True,
                        verbose_name="Job title",
                    ),
                ),
                (
                    "expected_salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Expected salary",
                    ),
                ),
                ("completed_welcome", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(create_interests, migrations.RunPython.noop),
    ]
